//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Library {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://example.org/jk/library")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://example.org/jk/library", IsNullable=false)]
    public partial class library {
        
        private bookinfo[] bookField;
        
        private authorinfo[] authorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("book")]
        public bookinfo[] book {
            get {
                return this.bookField;
            }
            set {
                this.bookField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("author")]
        public authorinfo[] author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://example.org/jk/library")]
    public partial class bookinfo {
        
        private authorref[] authorField;
        
        private string titleField;
        
        private string yearField;
        
        private languageinfo languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("author")]
        public authorref[] author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public languageinfo language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://example.org/jk/library")]
    public partial class authorref {
        
        private string authorref1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("authorref")]
        public string authorref1 {
            get {
                return this.authorref1Field;
            }
            set {
                this.authorref1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://example.org/jk/library")]
    public partial class authorinfo {
        
        private string[] nameField;
        
        private string surnameField;
        
        private string authoridField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public string[] name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string authorid {
            get {
                return this.authoridField;
            }
            set {
                this.authoridField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://example.org/jk/library")]
    public enum languageinfo {
        
        /// <remarks/>
        PL,
        
        /// <remarks/>
        EN,
        
        /// <remarks/>
        RU,
        
        /// <remarks/>
        TLH,
    }
}
